config/routes.rb
Rails.application.routes.draw do
  resources :oenologist_magazines
  resources :megazines
  resources :assignments
  resources :roles
  devise_for :users
  get 'home/index'
  resources :wines_oenologists
  resources :oenologists
  resources :wine_strains
  resources :strains
  resources :wines


  root to: "wines#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/models/megazine.rb
class Megazine < ApplicationRecord
  has_many :enologist_magazines
  has_many :enologist, through: :enologist_magazines
end

app/models/oenologist.rb
class Oenologist < ApplicationRecord

    has_many :enologist_magazines, dependent: :destroy
    has_many :magazines, through: :enologist_magazines, dependent: :destroy

    has_many :wine_enologists, dependent: :destroy
    has_many :wines, through: :wine_enologists, dependent: :destroy
    
end

app/models/oenologist_magazine.rb
class OenologistMagazine < ApplicationRecord
  belongs_to :enologist
  belongs_to :magazine
end

app/models/role.rb
class Role < ApplicationRecord
    has_many :assignments
    has_many :users, through: :assignments
end

app/models/strain.rb
class Strain < ApplicationRecord
    has_many :wine_strains
    has_many :wines, through: :wine_strains

    validates :name, uniqueness: { case_sensitive: false }
    validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: ["Normal", "Admin"] 
  has_many :assignments
  has_many :roles, through: :assignments 
  
end

app/models/wine.rb
class Wine < ApplicationRecord
    has_many :wine_strains, dependent: :destroy
    has_many :strains, through: :wine_strains, dependent: :destroy
    accepts_nested_attributes_for :wine_strains, allow_destroy: true

    validates :name, presence: true
    validates_associated :wine_strains
    validates_associated :strains

    has_many :wine_enologists, dependent: :destroy
    has_many :enologists, through: :wine_enologists, dependent: :destroy
    
end

app/models/wine_strain.rb
class WineStrain < ApplicationRecord
  belongs_to :wine
  belongs_to :strain
  accepts_nested_attributes_for :strain, allow_destroy: true

  validates :percentage, presence: true
end

app/models/wines_oenologist.rb
class WinesOenologist < ApplicationRecord
  belongs_to :wine
  belongs_to :oenologist
  accepts_nested_attributes_for :oenologist, allow_destroy: true
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @wines = Wine.includes(:wine_strains).all

  end
end

app/controllers/strains_controller.rb
class StrainsController < ApplicationController
  before_action :set_strain, only: %i[ show edit update destroy ]

  # GET /strains or /strains.json
  def index
    @strains = Strain.all
  end

  # GET /strains/1 or /strains/1.json
  def show
  end

  # GET /strains/new
  def new
    @strain = Strain.new
  end

  # GET /strains/1/edit
  def edit
  end

  # POST /strains or /strains.json
  def create
    @strain = Strain.new(strain_params)

    respond_to do |format|
      if @strain.save
        format.html { redirect_to strain_url(@strain), notice: "Strain was successfully created." }
        format.json { render :show, status: :created, location: @strain }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @strain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /strains/1 or /strains/1.json
  def update
    respond_to do |format|
      if @strain.update(strain_params)
        format.html { redirect_to strain_url(@strain), notice: "Strain was successfully updated." }
        format.json { render :show, status: :ok, location: @strain }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @strain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /strains/1 or /strains/1.json
  def destroy
    @strain.destroy

    respond_to do |format|
      format.html { redirect_to strains_url, notice: "Strain was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_strain
      @strain = Strain.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def strain_params
      params.require(:strain).permit(:name, :available)
    end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :authenticate_user!

  before_action :set_wine, only: %i[ show edit update destroy ]

  # GET /wines or /wines.json
  def index
    @wines = Wine.all
  end

  # GET /wines/1 or /wines/1.json
  def show
  end

  # GET /wines/new
  def new
    @wine = Wine.new
    @wine.wine_strains.build

  end

  # GET /wines/1/edit
  def edit
  end

  # POST /wines or /wines.json
  def create
    @wine = Wine.new(wine_params)

    respond_to do |format|
      if @wine.save
        format.html { redirect_to wine_url(@wine), notice: "Wine was successfully created." }
        format.json { render :show, status: :created, location: @wine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wines/1 or /wines/1.json
  def update
    respond_to do |format|
      if @wine.update(wine_params)
        format.html { redirect_to wine_url(@wine), notice: "Wine was successfully updated." }
        format.json { render :show, status: :ok, location: @wine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1 or /wines/1.json
  def destroy
    @wine.destroy

    respond_to do |format|
      format.html { redirect_to wines_url, notice: "Wine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wine_params
      params.require(:wine).permit(:name, {enologist_ids: []},wine_strains_attributes: [:id, :strain_id,:percentage, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/megazines_helper.rb
module MegazinesHelper
end

app/helpers/oenologists_helper.rb
module OenologistsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/strains_helper.rb
module StrainsHelper
end

app/helpers/wine_strains_helper.rb
module WineStrainsHelper
end

app/helpers/wines_helper.rb
module WinesHelper
    def strains_for_select
        Strain.order(:name).collect { |g| [g.name, g.id]}
    end
    def oenologist_for_select
        Oenologist.order(:name).collect { |g| [g.name, g.id]}
    end
end

app/views/strains/_form.html.erb
<%= form_with(model: strain, local: true) do |form| %>
  <% if strain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(strain.errors.count, "error") %> prohibited this strain from being saved:</h2>

      <ul>
      <% strain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :available %>
    <%= form.check_box :available %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/strains/edit.html.erb
<h1>Editing Strain</h1>

<%= render 'form', strain: @strain %>

<%= link_to 'Show', @strain %> |
<%= link_to 'Back', strains_path %>

app/views/strains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Strains</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Available</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @strains.each do |strain| %>
      <tr>
        <td><%= strain.name %></td>
        <td><%= strain.available %></td>
        <td><%= link_to 'Show', strain %></td>
        <td><%= link_to 'Edit', edit_strain_path(strain) %></td>
        <td><%= link_to 'Destroy', strain, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Strain', new_strain_path %>

app/views/strains/new.html.erb
<h1>New Strain</h1>

<%= render 'form', strain: @strain %>

<%= link_to 'Back', strains_path %>

app/views/strains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @strain.name %>
</p>

<p>
  <strong>Available:</strong>
  <%= @strain.available %>
</p>

<%= link_to 'Edit', edit_strain_path(@strain) %> |
<%= link_to 'Back', strains_path %>

app/views/wines/_form.html.erb
<%= form_with(model: wine, local: true) do |form| %>
  <% if wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
      <% wine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  
    <div id="wine_strains" class="form-group">
    <%= form.fields_for :wine_strains do |strain_wine_form| %>
    <%= render 'wine_strain_fields', f: strain_wine_form %>
    <% end %>
    
    <div class="links form-inline">
      <%= link_to_add_association 'add strain', form, :wine_strains %>
    </div>
  </div>


  <div id="wine_strains" class="form-group">
    <%= form.fields_for :wine_strains do |strain_wine_form| %>
    <%= render 'wine_strain_fields', f: strain_wine_form %>
    <% end %>
    
    <div class="links form-inline">
      <%= link_to_add_association 'add strain', form, :wine_strains %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wines/_wine_strain_fields.html.erb
<div class="nested-fields form-inline">
    <%= f.select :strain_id, strains_for_select, {}, class: 'custom-select mx-sm-3 mb-2' %>
    <div class="form-group mr-sm-3 mb-2">
        <%= f.label :percentage, '%' %>
        <%= f.text_field :percentage, class: 'form-control mr-sm-3' %>
    </div>
    <%= link_to_remove_association 'remove strain', f %>
</div> 

app/views/wines/edit.html.erb
<h1>Editing Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Show', @wine %> |
<%= link_to 'Back', wines_path %>

app/views/wines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Strains</th>
      <th>Grade</th>
      <th>Enologists</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
   <tr>
    <% @wines.each do |wine| %>
        <td><%= wine.name %></td>
          <td>
          <% WineStrain.where(wine_id: wine.id).each do |wine_strain| %>
            <li><%= wine_strain.strain.name %><%= " (#{wine_strain.percentage}%)" %></li>
          <% end %>
        </td>
        <td>
          <% WinesOenologist.where(wine_id: wine.id).each do |wine_enologist| %>
            <li><%= wine_enologist.grade %></li>
          <% end %>
        </td>        
      
        <td>
          <% WinesOenologist.where(wine_id: wine.id).each do |wine_enologist| %>
            <li><%= wine_enologist.oenologist.name %></li>
          <% end %>
        </td>
          <td><%= link_to 'Show', wine %></td>
          <td><%= link_to 'Edit', edit_wine_path(wine) %></td>
          <td><%= link_to 'Destroy', wine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

  <%= link_to 'New Wine', new_wine_path %>

<br>

<%= button_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn btn-primary mx-4'  %>

app/views/wines/new.html.erb
<h1>New Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Back', wines_path %>

app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wine.name %>
</p>

<%= link_to 'Edit', edit_wine_path(@wine) %> |
<%= link_to 'Back', wines_path %>